### ISSUE TITLE
default formatting of data fields in contact

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#239]
This may be due to importing, but i am not seeing that format for these are enforced.
Ideas?

PHONE
OTHERPHONE
MAILINGCOUNTRY
MAILINGSTATE
MOBILEPHONE
NPE01__HOME_ADDRESS__C

I can pre-munge the data, but curious what we want it to be and if we can add enforcement?

**Comment by deb761** [comment]
I did a bit of poking around, and phone number is a string.  Sounds like the formatting is a front-end thing based on locale.

Different countries have different formatting for phone numbers, and since Atlas has clients in other countries, you probably don't want to force all phones to the same format.

**Comment by atlasjen** [comment]
okey dokey. i think i'll have sandeep update the form assembly forms to enforce some formatting to help our data be cleaner.
________________________________
