### ISSUE TITLE
Determine how to do scheduled/reoccuring emails in salesforce

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#506]
I am assuming this is not code related, but more just needs to be explained.
We have a lot of cases where we want to schedule emails to repeat. Some would be individualized per person, or use fields we can pull from salesforce. Nothing that is more complex than we can get out of the contact.

Can you please look into how to do this ? I am hoping it doesn't require flows and is something that would be easy for Laura to be able to schedule, but let me know.

Adding to 1.6 but i don't think it is part of a release (at least hoping it doesn't require any code/flows)

**Comment by mguillendev** [comment]
I would swear that the only way to do this in Salesforce is with an automation made with Workflow rules, Process Builder or Flow. The point is that both Workflow rules and Process Builder are the little old brothers of Flow. Flow does the same and more things than Workflow rules and Process Builder and in fact if you try to create either of these two, the org warns you that they are outdated and to please don't use them and use Flow instead.

Depending on the case, the flow could be created so that Laura does not have to do anything. 

Please tell me a concrete case that you want to automate, to do the test. For example: when a new contact is created, send an email welcoming him/her and automate an email to send him/her a congratulation email every time it is his/her birthday.

**Comment by atlasjen** [comment]
So the first use case i am thinking of wouldn't be triggered but scheduled by a human. Here is an example- a new team starts training. We would like an email to go to the client weekly to remind them to complete their logs. we want an email to go to their team facilitators every 2 weeks to remind them to complete the training logs.

Right now i use microsoft flows to control this and i can't customize it per person. Ideally it would be w/in salesforce and we could customize

- preferred name
- url for the form (we would pass some data from salesforce as part of the url)
- frequency of email
and then easily add or remove people this is scheduled to go to.
So this would be 2 different emails that would be scheduled, one for clients one for facilitators.

Next use case- would be monthly reminders that go to team facilitators to submit CUEs. So same idea as above,
- preferred name
- frequency
- url for the form


Ultimately, yes, we will want to setup triggers to automate emails based on various dates, but right now i am looking at how to schedule something manually.  I suppose it could be automated based on a change of status for the team. that could be another option..  

I have used flows some, i'm not sure how easy they are to customize and schedule like this, but a flow makes sense.

**Comment by atlasjen** [comment]
also moving this to 1.7

**Comment by atlasjen** [comment]
closing. this is replaced by #546
