### ISSUE TITLE
Add in historical reporting

### ISSUE THREAD

**Issue by atlasjen** [Atlas-Assistance-Dogs/atlas-dogs#511]
Per what we discussed, add in options for trend reporting so we can track numbers month to month that i presently only have snapshots of.

**Comment by mguillendev** [comment]
I I have already set up snapshot reporting in Salesforce. I have set it to do the daily data recording for testing purposes. When everything is checked and finished, I will set it to monthly so that it will be done every month on the day and time of your choice. 

**What I have done so far:**
- I have created a "Snapshot Report Test" report folder to which only I have access for now. 
- Inside that folder, I have created the report "Snapshot report Client count_Test" to which only I have access for now. That report is the same as the source report of the first dashboard component, the one that counts how many clients there are with different statuses. 
- I have created a custom object "Client count Snapshot" which you have access to but cannot find. 
- I have created a "Reporting snapshots" in Setup called "Client Count Snapshot" and I have mapped fields between the created report and the object, so that it creates a record in the object with the values of the report at the time the record is created (when it is scheduled: daily, monthly...). **An important thing about this Reporting Snapshots is that Jennifer Kolar is the running user. If Jen's user is deactivated, you must remember to change the running user of the reporting snapshots for one that is active, otherwise it will stop saving the data every month.**

**Next steps:** Now I have to wait a few days for it to generate some data and then prepare a report where I compare the data of the different days. 

If you want me to give you access to some (or all) of these elements, please tell me to what and to whom.

**Comment by atlasjen** [comment]
i'm happy waiting a few days until there is some data and then would love to have you show me how to use it.

**Comment by mguillendev** [comment]
This issue is almost resolved. It only remains to see what display options we can give to the Client Locations graph: 
there are 2 variables to group by: the mailing state/province and the client status. For now I can't find a way to group by the two variables and have an X axis that is Created date. Next month, when there are records with another created date, we can think how to make the graph.

**Comment by atlasjen** [comment]
closing. this is all good.
